### ISSUE TITLE
How to use 

### ISSUE THREAD

**Issue by AmerShanan** [choochootrain/android-offline-forms#1]
How to use  and import

**Comment by choochootrain** [comment]
Release is available at https://github.com/choochootrain/android-offline-forms/releases

Change [DEBUG_URL](https://github.com/choochootrain/android-offline-forms/blob/master/app/src/main/java/com/choochootrain/offlineform/app/forms/builder/FormBuilder.java#L22) or call [setTarget](https://github.com/choochootrain/android-offline-forms/blob/master/app/src/main/java/com/choochootrain/offlineform/app/forms/builder/FormBuilder.java#L108) to the target for the form, then recompile.
